/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microtechmd_pda_app_service_service_control_platform_JNIInterface */

#ifndef _Included_com_microtechmd_pda_app_service_service_control_platform_JNIInterface
#define _Included_com_microtechmd_pda_app_service_service_control_platform_JNIInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microtechmd_pda_app_service_service_control_platform_JNIInterface
 * Method:    send
 * Signature: (IIIIII[B)I
 */
JNIEXPORT jint JNICALL Java_com_microtechmd_pda_1app_service_service_1control_platform_JNIInterface_send
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     com_microtechmd_pda_app_service_service_control_platform_JNIInterface
 * Method:    receive
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_microtechmd_pda_1app_service_service_1control_platform_JNIInterface_receive
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_microtechmd_pda_app_service_service_control_platform_JNIInterface
 * Method:    query
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_microtechmd_pda_1app_service_service_1control_platform_JNIInterface_query
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_microtechmd_pda_app_service_service_control_platform_JNIInterface
 * Method:    switchFrame
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_microtechmd_pda_1app_service_service_1control_platform_JNIInterface_switchFrame
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_microtechmd_pda_app_service_service_control_platform_JNIInterface
 * Method:    switchLink
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_microtechmd_pda_1app_service_service_1control_platform_JNIInterface_switchLink
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
